---
output: html_document
title: >
  Statistical Data Science 1: Fall 2023
author: "STA 35A"

---

**Instructor**: Xiao Hui Tai (xtai [at] ucdavis [dot] edu)

**TA**: Jedidiah Harwood (jedharwood [at] ucdavis [dot] edu)

**Class time**:   
Lectures are Mondays, Wednesdays and Fridays, 11-11:50 AM at Wellman Hall 216.  
Discussions (labs) are run by Jedidiah Harwood on Thursdays 12:10-1 PM (Section A01), 1:10-2 PM (Section A02) at TLC 2212.

**Office hours**:  
Jedidiah Harwood: Tuesdays and Thursdays 10-11 AM at MSB 1117   
Xiao Hui Tai: Mondays 2:30-3:30 PM at MSB 4242

**Syllabus**: [here](https://xhtai.github.io/statdatasci/syllabus_35A_F23.html).

**Piazza**: [here](https://piazza.com/ucdavis/fall2023/sta035aa01a02fq2023/). 

**Textbooks**:
There are three required textbooks. They are all available online and are free. 

1. R for Data Science by Hadley Wickham and Garrett Grolemund. 1st Edition, 2017. Available [here](https://r4ds.had.co.nz/index.html).
2. Introduction to Modern Statistics by Mine Çetinkaya-Rundel and Johanna Hardin. 1st Edition, 2021. Available [here](https://openintro-ims.netlify.app/index.html).
3. OpenIntro Statistics by David Diez, Mine Cetinkaya-Rundel and Christopher Barr. 4th Edition, 2019. Available [here](https://www.openintro.org/book/os/).

There will sometimes be additional (optional) reading from: 

1. Art of R Programming by Norman Matloff. 2011. (Look on Google)

## Class Schedule

### Week 1: Introduction, overview of data types	
- Wed Sept 27: Introduction and R Basics
  - Notes: [Lecture 1](https://xhtai.github.io/statdatasci/lectures/lecture1/lecture1.html)
  - Reading: 
    - R for Data Science Chapters 1, 2, 27

- Fri Sept 29: Overview of data types and data structures, vectors
  - Notes: [Lecture 2](https://xhtai.github.io/statdatasci/lectures/lecture2/lecture2.html)
  - Reading:
    - R for Data Science Chapter 4, 20
    - Additional reading: Matloff Chapter 2



### Week 2: Overview of data types
- Mon Oct 2: More on vectors, arrays
  - Notes: [Lecture 3](https://xhtai.github.io/statdatasci/lectures/lecture3/lecture3.html)
  - Reading:
    - R for Data Science Chapter 20
    - Additional reading: Matloff Chapter 3

- Wed Oct 4: Arrays, matrices, lists
  - Notes: [Lecture 4](https://xhtai.github.io/statdatasci/lectures/lecture4/lecture4.html)
  - Reading:
    - R for Data Science Chapter 20
    - Additional reading: Matloff Chapters 3, 4

- Fri Oct 6: Lists, data frames, exploratory data analysis
  - Notes: [Lecture 5](https://xhtai.github.io/statdatasci/lectures/lecture5/lecture5.html)
  - Reading:
    - Additional reading: Matloff Chapter 5
  - Homework 1: [Html](https://xhtai.github.io/statdatasci/homework/homework1/HW1.html) [Rmd](https://xhtai.github.io/statdatasci/homework/homework1/HW1.Rmd)



### Week 3: Data manipulation and data visualization tools
- Mon Oct 9: Exploratory data analysis, data manipulation tools
  - Notes: [Lecture 6](https://xhtai.github.io/statdatasci/lectures/lecture6/lecture6.html)
  - Reading:
    - R for Data Science Chapter 5

- Wed Oct 11: Data manipulation and visualization tools
  - Notes: [Lecture 7](https://xhtai.github.io/statdatasci/lectures/lecture7/lecture7.html)
  - Reading:
    - R for Data Science Chapter 3

- Fri Oct 13: Data visualization tools
  - Notes: [Lecture 8](https://xhtai.github.io/statdatasci/lectures/lecture8/lecture8.html)
  - Reading:
    - R for Data Science Chapter 3
  - Homework 2: [Html](https://xhtai.github.io/statdatasci/homework/homework2/HW2.html) [Rmd](https://xhtai.github.io/statdatasci/homework/homework2/HW2.Rmd)


### Week 4: Data visualization tools, Descriptive statistics
- Mon Oct 16: Data visualization tools, descriptive statistics
  - Notes: [Lecture 9](https://xhtai.github.io/statdatasci/lectures/lecture9/lecture9.html)
  - Reading:
    - Open Intro Statistics Chapter 1

- Wed Oct 18: Review

- Fri Oct 20: Midterm 1


### Week 5: Descriptive statistics
- Mon Oct 23: Describing numerical distributions
  - Notes: [Lecture 10](https://xhtai.github.io/statdatasci/lectures/lecture10/lecture10.html)
  - Reading:
    - Open Intro Statistics Chapter 2

- Wed Oct 25: Numerical and categorical data
  - Notes: [Lecture 11](https://xhtai.github.io/statdatasci/lectures/lecture11/lecture11.html)
  - Reading:
    - R for Data Science Chapter 7

- Fri Oct 27: Numerical and categorical data
  - Notes: [Lecture 12](https://xhtai.github.io/statdatasci/lectures/lecture12/lecture12.html)
  - Homework 3: [Html](https://xhtai.github.io/statdatasci/homework/homework3/HW3.html) [Rmd](https://xhtai.github.io/statdatasci/homework/homework3/HW3.Rmd)

### Week 6: Introduction to probability
- Mon Oct 30: Introduction to probability
  - Notes: [Lecture 13](https://xhtai.github.io/statdatasci/lectures/lecture13/lecture13.html)
  - Reading:
    - Open Intro Statistics Chapter 3.1

- Wed Nov 1: Conditional, marginal and joint probability
  - Notes: [Lecture 14](https://xhtai.github.io/statdatasci/lectures/lecture14/lecture14.html)
  - Reading:
    - Open Intro Statistics Chapter 3.2

- Fri Nov 3: Bayes' Theorem; Random variables
  - Notes: [Lecture 15](https://xhtai.github.io/statdatasci/lectures/lecture15/lecture15.html)
  - Reading:
    - Open Intro Statistics Chapter 3.4, 3.5
  - Homework 4: [Html](https://xhtai.github.io/statdatasci/homework/homework4/HW4.html) [Rmd](https://xhtai.github.io/statdatasci/homework/homework4/HW4.Rmd)

### Week 7: Common distributions
- Mon Nov 6: Bernoulli and binomial distribution
  - Notes: [Lecture 16](https://xhtai.github.io/statdatasci/lectures/lecture16/lecture16.html)
  - Reading:
    - Open Intro Statistics Chapter 4.3

- Wed Nov 8: Binomial distribution
  - Notes: [Lecture 17](https://xhtai.github.io/statdatasci/lectures/lecture17/lecture17.html)
  - Reading:
    - Open Intro Statistics Chapter 4.5

- Fri Nov 10: Veterans Day
  - Homework 5: [Html](https://xhtai.github.io/statdatasci/homework/homework5/HW5.html) [Rmd](https://xhtai.github.io/statdatasci/homework/homework5/HW5.Rmd)

### Week 8: Poisson and normal distribution
- Mon Nov 13: Poisson and Normal distribution
  - Notes: [Lecture 18](https://xhtai.github.io/statdatasci/lectures/lecture18/lecture18.html)
  - Reading:
    - Open Intro Statistics Chapter 4.1

- Wed Nov 15: Review

- Fri Nov 17: Midterm 2


### Week 9: Normal distribution
- Mon Nov 20: Normal distribution
  - Notes: [Lecture 19](https://xhtai.github.io/statdatasci/lectures/lecture19/lecture19.html)
  - Reading:
    - Open Intro Statistics Chapter 5.1

- Wed Nov 22, Fri Nov 24: Thanksgiving

### Week 10: Sampling distributions, confidence intervals
- Mon Nov 27: Sampling distribution of sample mean
  - Notes: [Lecture 20](https://xhtai.github.io/statdatasci/lectures/lecture20/lecture20.html)
  - Homework 6: [Html](https://xhtai.github.io/statdatasci/homework/homework6/HW6.html) [Rmd](https://xhtai.github.io/statdatasci/homework/homework6/HW6.Rmd)

- Wed Nov 29: Sample proportion, Confidence intervals
  - Notes: [Lecture 21](https://xhtai.github.io/statdatasci/lectures/lecture21/lecture21.html)
  - Reading:
    - Open Intro Statistics Chapter 5.2

- Fri Dec 1: Confidence intervals for population mean and proportion
  - Notes: [Lecture 22](https://xhtai.github.io/statdatasci/lectures/lecture22/lecture22.html)
  - Reading:
    - Open Intro Statistics Chapter 7.1.1-7.1.4

### Week 11: Hypothesis testing
- Mon Dec 4: Hypothesis testing framework and errors
  - Notes: [Lecture 23](https://xhtai.github.io/statdatasci/lectures/lecture23/lecture23.html)
  - Reading:
    - Open Intro Statistics Chapter 5.3
  - Homework 7:
<!-- - Wed Dec 6: Hypothesis testing for population mean and proportion  -->
<!--   - Notes:  -->
<!--   - Reading: -->
<!--     - Open Intro Statistics Chapter 6.1 -->
<!-- - Fri Dec 8: Confidence intervals and one-sided tests  -->
<!--   - Notes:  -->

