---
output: html_document
title: >
  Statistical Data Science 1: Fall 2024
author: "STA 35A"

---

**Instructor**: Xiao Hui Tai (xtai [at] ucdavis [dot] edu)

**TA**: Oscar Rivera (ogrivera [at] ucdavis [dot] edu)

**Class time**:   
Lectures are Mondays, Wednesdays and Fridays, 11-11:50 AM at Wellman Hall 226.  
Discussions (labs) are run by Oscar Rivera on Thursdays 12:10-1 PM (Section A01), 1:10-2 PM (Section A02) at TLC 2212.

**Office hours**:  
Oscar Rivera: Thursday 3-4 PM and Friday 1-2 PM at MSB 1117  
Xiao Hui Tai: Wednesdays 1-2 PM at MSB 4242

**Syllabus**: [here](https://xhtai.github.io/statdatasci/syllabus_35A_F24.html).

**Piazza**: [here](https://piazza.com/ucdavis/fall2024/sta035aa01a02fq2024/). 

**Textbooks**:
There are three required textbooks. They are all available online and are free. 

1. R for Data Science by Hadley Wickham, Mine Çetinkaya-Rundel and Garrett Grolemund. 2nd Edition, 2023. Available [here](https://r4ds.had.co.nz/).
2. Introduction to Modern Statistics by Mine Çetinkaya-Rundel and Johanna Hardin. 2nd Edition, 2024. Available [here](https://openintro-ims.netlify.app/index.html).
3. OpenIntro Statistics by David Diez, Mine Çetinkaya-Rundel and Christopher Barr. 4th Edition, 2019. Available [here](https://www.openintro.org/book/os/).

There will sometimes be additional (optional) reading from: 

1. Art of R Programming by Norman Matloff. 2011. (Look on Google)

## Class Schedule

### Week 1: Introduction, overview of data types	
- Wed Sept 25: Introduction and R Basics
  - Notes: [Lecture 1](https://xhtai.github.io/statdatasci/lectures/lecture1/lecture1.html)
  - Reading: 
    - R for Data Science Chapters 1, 28

- Fri Sept 27: Overview of data types and data structures, vectors
  - Notes: [Lecture 2](https://xhtai.github.io/statdatasci/lectures/lecture2/lecture2.html)
  - Reading:
    - R for Data Science Chapter 2
    - Additional reading: Matloff Chapter 2

### Week 2: Overview of data types
- Mon Sept 30: More on vectors, arrays
  - Notes: [Lecture 3](https://xhtai.github.io/statdatasci/lectures/lecture3/lecture3.html)
  - Reading:
    - Additional reading: Matloff Chapter 3

- Wed Oct 2: Arrays, matrices, lists
  - Notes: [Lecture 4](https://xhtai.github.io/statdatasci/lectures/lecture4/lecture4.html)
  - Reading:
    - Additional reading: Matloff Chapters 3, 4

- Fri Oct 4: Lists, data frames
  - Notes: [Lecture 5](https://xhtai.github.io/statdatasci/lectures/lecture5/lecture5.html)
  - Reading:
    - Additional reading: Matloff Chapter 4, 5
  - Homework 1: [Html](https://xhtai.github.io/statdatasci/homework/homework1/HW1.html) [qmd](https://xhtai.github.io/statdatasci/homework/homework1/HW1.qmd)

### Week 3: Data frames, data manipulation and data visualization tools
- Mon Oct 7: Data frames, exploratory data analysis, data manipulation tools
  - Notes: [Lecture 6](https://xhtai.github.io/statdatasci/lectures/lecture6/lecture6.html)
  - Reading:
    - R for Data Science Chapter 3

- Wed Oct 9: Data manipulation tools
  - Notes: [Lecture 7](https://xhtai.github.io/statdatasci/lectures/lecture7/lecture7.html)
    - [Hotels data](https://github.com/xhtai/xhtai.github.io/blob/master/statdatasci/lectures/lecture6/data/hotels.csv)
  - Reading:
    - R for Data Science Chapter 3

- Fri Oct 11: Data visualization tools
  - Notes: [Lecture 8](https://xhtai.github.io/statdatasci/lectures/lecture8/lecture8.html)
  - Reading:
    - R for Data Science Chapter 1
  - Homework 2: [Html](https://xhtai.github.io/statdatasci/homework/homework2/HW2.html) [qmd](https://xhtai.github.io/statdatasci/homework/homework2/HW2.qmd)


### Week 4: Data visualization tools, Descriptive statistics
- Mon Oct 14: Data visualization tools, descriptive statistics
  - Notes: [Lecture 9](https://xhtai.github.io/statdatasci/lectures/lecture9/lecture9.html)
  - Reading:
    - Open Intro Statistics Chapter 1

- Wed Oct 16: Review

- Fri Oct 18: Midterm 1

### Week 5: Descriptive statistics
- Mon Oct 21: Describing numerical distributions
  - Notes: [Lecture 10](https://xhtai.github.io/statdatasci/lectures/lecture10/lecture10.html)
  - Reading:
    - Open Intro Statistics Chapter 2

- Wed Oct 23: Numerical data
  - Notes: [Lecture 11](https://xhtai.github.io/statdatasci/lectures/lecture11/lecture11.html)
  - Reading:
    - R for Data Science Chapter 10

- Wed Oct 25: Categorical data
  - Notes: [Lecture 12](https://xhtai.github.io/statdatasci/lectures/lecture12/lecture12.html)
  - Homework 3: [Html](https://xhtai.github.io/statdatasci/homework/homework3/HW3.html) [qmd](https://xhtai.github.io/statdatasci/homework/homework3/HW3.qmd)

### Week 6: Introduction to probability
- Mon Oct 28: Introduction to probability
  - Notes: [Lecture 13](https://xhtai.github.io/statdatasci/lectures/lecture13/lecture13.html)
  - Reading:
    - Open Intro Statistics Chapter 3.1

- Wed Oct 30: Conditional, marginal and joint probability
  - Notes: [Lecture 14](https://xhtai.github.io/statdatasci/lectures/lecture14/lecture14.html)
  - Reading:
    - Open Intro Statistics Chapter 3.2

- Fri Nov 1: Bayes' Theorem; Random variables
  - Notes: [Lecture 15](https://xhtai.github.io/statdatasci/lectures/lecture15/lecture15.html)
  - Reading:
    - Open Intro Statistics Chapter 3.4  
  - Homework 4: [Html](https://xhtai.github.io/statdatasci/homework/homework4/HW4.html) [qmd](https://xhtai.github.io/statdatasci/homework/homework4/HW4.qmd)

### Week 7: Common distributions
- Mon Nov 4: Continuous random variabnles, Bernoulli distribution
  - Notes: [Lecture 16](https://xhtai.github.io/statdatasci/lectures/lecture16/lecture16.html)
  - Reading:
    - Open Intro Statistics Chapter 3.5, 4.3

- Wed Nov 6: Binomial distribution
  - Notes: [Lecture 17](https://xhtai.github.io/statdatasci/lectures/lecture17/lecture17.html)
  - Reading:
    - Open Intro Statistics Chapter 4.3

- Fri Nov 8: Poisson distribution
  - Notes: [Lecture 18](https://xhtai.github.io/statdatasci/lectures/lecture18/lecture18.html)
  - Reading:
    - Open Intro Statistics Chapter 4.5
  - Homework 5: [Html](https://xhtai.github.io/statdatasci/homework/homework5/HW5.html) [qmd](https://xhtai.github.io/statdatasci/homework/homework5/HW5.qmd)

### Week 8 
- Mon Nov 11: Veterans Day 

- Wed Nov 13: Review

- Fri Nov 15: Midterm 2

### Week 9: Normal distribution, sampling distributions
- Mon Nov 20: Normal distribution
  - Notes: [Lecture 19](https://xhtai.github.io/statdatasci/lectures/lecture19/lecture19.html)
  - Reading:
    - Open Intro Statistics Chapter 4.1

- Wed Nov 22: Sampling distributions 
  - Notes: [Lecture 20](https://xhtai.github.io/statdatasci/lectures/lecture20/lecture20.html)
  - Reading:
    - Open Intro Statistics Chapter 5.1

- Fri Nov 24: Sample proportion, Confidence intervals
  - Notes: [Lecture 21](https://xhtai.github.io/statdatasci/lectures/lecture21/lecture21.html)
  - Reading:
    - Open Intro Statistics Chapter 5.2
  - Homework 6: [Html](https://xhtai.github.io/statdatasci/homework/homework6/HW6.html) [qmd](https://xhtai.github.io/statdatasci/homework/homework6/HW6.qmd)


### Week 10: Confidence intervals
- Mon Nov 25: Confidence intervals for population mean and proportion
  - Notes: [Lecture 22](https://xhtai.github.io/statdatasci/lectures/lecture22/lecture22.html)
  - Reading:
    - Open Intro Statistics Chapter 7.1.1-7.1.4
